version: '3.8'

services:
  front:
    build: ./frontend/sklad
    image: scalepilot-front
    container_name: scalepilot-front
    ports:
      - 8072:80
  back:
    build: ./backend/sklad
    image: scalepilot-back
    container_name: scalepilot-back
    ports:
      - 8082:8082