# ===============================
#            DATABASE
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sklad
    username: postgres
    password: maxim23
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
#    show-sql: true # Set to true if you want to see SQL queries in the console
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
# If you want to enable Hibernate's second-level caching, add the following:
#   jpa:
#     properties:
#       hibernate:
#         cache:
#           use_second_level_cache: true
#           region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  output:
    ansi:
      enabled: ALWAYS
#  spring:
#    servlet:
#      multipart:
#        max-file-size: 35MB
#        max-request-size: 35MB
#        resolve-lazily: true

# ===============================
#            SERVER
# ===============================
server:
  port: 8082
#  tomcat:
#    max-swallow-size: 4096MB
#    max-http-post-size: 4096MB

# ===============================
# Security
# ===============================
application:
  security:
    jwt:
      secret-key: 86256E326557E632345366A575657538785262F413F4428440472B4B066B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

