# ===============================
#            DATABASE
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sklad
    username: postgres
    password: maxim23
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
  config:
    import: optional:secrets.yaml

# ===============================
#            SERVER
# ===============================
server:
  port: 8082
# ===============================
# Security
# ===============================
application:
  security:
    jwt:
      expiration: 86400000
      refresh-token:
        expiration: 604800000
